import type { RenderContext, DocumentComponentConfig } from "../types.js";
import { renderAllComponents } from "../registry.js";

export interface ReportOptions {
  title: string;
  date?: string;
  components: DocumentComponentConfig[];
}

export function generateReportHtml(options: ReportOptions, ctx: RenderContext): string {
  const brandColor = ((ctx.designTokens as any)?.color?.brand?.["500"]) ?? "#3b82f6";
  const fontFamily = ((ctx.designTokens as any)?.typography?.fontFamily?.sans) ?? "system-ui, sans-serif";

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${options.title}</title>
<style>
  :root { --brand-500: ${brandColor}; }
  body { font-family: ${fontFamily}; max-width: 900px; margin: 0 auto; padding: 32px 24px; color: #0f172a; line-height: 1.6; }
  h1, h2, h3 { color: var(--brand-500); }
</style>
</head>
<body>
${ctx.brandAssets?.logo ? `<header style="display:flex;align-items:center;gap:12px;padding-bottom:16px;border-bottom:2px solid var(--brand-500);margin-bottom:32px;"><img src="${ctx.brandAssets.logo}" alt="logo" style="height:36px;" /><h1 style="font-size:24px;margin:0;">${options.title}</h1></header>` : `<h1>${options.title}</h1>`}
${options.date ? `<p style="color:#64748b;font-size:14px;">${options.date}</p>` : ""}
${renderAllComponents(options.components, ctx)}
<footer style="margin-top:48px;padding-top:16px;border-top:1px solid #e2e8f0;text-align:center;font-size:12px;color:#94a3b8;">Generated by AI Factory</footer>
</body>
</html>`;
}
